//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18449
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEngine;
using System;
using System.Collections;

namespace MMFW
{
		public class MMGGround
		{
				public void create ()
				{			
						for (float z = 0; z < 10; z += 0.1f) {
								GameObject cube1 = GameObject.CreatePrimitive (PrimitiveType.Cube);
								cube1.transform.position = new Vector3 (0.5f + z, 0.5f + z / 10f, 5f + z);
								cube1.renderer.material.color = Color.red;
						}
				}
		}
}

