//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18449
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;

namespace MMFW
{
		public class UNAGSprite
		{
				private AnimationPlayer sprite;
				private SpriteEffects flip = SpriteEffects.None;
				private Animation runAnimation;
				private Vector2 position;
		
				public void load (ContentManager content)
				{
						runAnimation = new Animation (content.Load<Texture2D> ("Sprites/m-suraimu"), 0.1f, true);
				}

				public void Reset ()
				{
						sprite.PlayAnimation (runAnimation);
				}
        
				public void Update ()
				{
						sprite.PlayAnimation (runAnimation);
				}

				public void movePosition (Vector2 v)
				{
						position += v;
				}

				public void Draw (GameTime gameTime, SpriteBatch spriteBatch)
				{
						sprite.Draw (gameTime, spriteBatch, position, flip);
				}
		}
}

