//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18449
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Microsoft.Xna.Framework.Input;

namespace MMFW
{
		public static class UNAInput
		{
		}

		public static class UNAIKeyboard
		{
		
				/// <summary>
				/// 
				/// </summary>
				/// <returns><c>true</c>, if press was ised, <c>false</c> otherwise.</returns>
				/// <param name="c">C.</param>
				public static bool isPress (Keys c)
				{
						return Keyboard.GetState ().IsKeyDown (c);
				}
		
				private static bool[] press_state = new bool[256];
		
				/// <summary>
				/// 押した
				/// </summary>
				public static bool get (Keys c)
				{
						if (!press_state [(int)c] && isPress (c)) {
								press_state [(int)c] = true;
								return true;
						} else if (!isPress (c)) {
								press_state [(int)c] = false;
								return false;
						} else {
								return false;
						}
				}
		}
}

